### PR TITLE
Modernize the build setup

### PR DESCRIPTION
**Pull request by lemire**
This should improve the build setup.

### CODE REVIEW

**Comment by lemire** [comment]
@aviggiano 

The proposed build setup will compile to static libraries:

```
option(BUILD_SHARED_LIBS "use shared libraries" OFF)
```

If one must have dynamic libraries then this should not be OFF, but then you need to make sure that the linker finds the location of the dynamic library.

**Comment by lemire** [comment]
I have pushed an update which should generate a shared library as well.

**Comment by lemire** [comment]
@aviggiano I pushed another update.

**Comment by lemire** [comment]
@aviggiano  I am sure we can improve the PR.

Get in touch with me if I can help further. There is obviously a lot of interest for this project and I am available to help.

**Comment by xl-xueling** [comment]
@aviggiano @lemire   thanks all of you，this project is very very useful !

**Comment by lemire** [comment]
@aviggiano I have updated the PR with something that I hope is even better than your patch.

**Pull request merged**
