### PR TITLE
fix memory leaking caused by `r.max` and `r.min`

### PR DESCRIPTION
**Pull request by arthurkiller**

### CODE REVIEW

**Comment by aviggiano** [comment]
Interesting! Is it possible to add a test to catch this? I'm not sure if the ones that use valgrind are 100% accurate now that you found this

**Comment by lemire** [comment]
@aviggiano Valgrind *should* catch all memory leaks. It would be interesting to find out that it does not.

**Comment by arthurkiller** [comment]
I found this memory leak via 'leak'

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
Sent from my iPhone

**Comment by arthurkiller** [comment]
`leaks` reports that:
```
Path:            /Users/USER/*/redis-server
Load Address:    0x108432000
Identifier:      redis-server
Version:         ???
Code Type:       X86-64
Platform:        macOS
Parent Process:  tclsh8.5 [44989]

Date/Time:       2021-07-14 15:17:31.120 +0800
Launch Time:     2021-07-14 15:17:27.944 +0800
OS Version:      macOS 11.1 (20C69)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         11.5M
Physical footprint (peak):  12.1M
----

leaks Report Version: 4.0
Process 46651: 30663 nodes malloced for 25584 KB
Process 46651: 6 leaks for 480 total leaked bytes.

    6 (480 bytes) << TOTAL >>

      2 (160 bytes) ROOT LEAK: 0x7fd24af72b10 [128]
         1 (32 bytes) 0x7fd24af72af0 [32]

      2 (160 bytes) ROOT LEAK: 0x7fd24af72c70 [128]
         1 (32 bytes) 0x7fd24af5f4b0 [32]

      2 (160 bytes) ROOT LEAK: 0x7fd24e02d070 [128]
         1 (32 bytes) 0x7fd24e02d050 [32]
```

**Comment by arthurkiller** [comment]
I'm not sure why you guys did not found this leak by `Valgrind`, and `leaks` is also new to me. 

But after I added call to `RedisModule_AutoMemory`, everything works well 😁

**Comment by aviggiano** [comment]
Cool, I didn't know about it. 
In any case, it's much more probable that our Valgrind tests are not 100% correct, so I'll have to take a look at them. I'll just add some tests to catch this issue before merging this PR

**Comment by aviggiano** [comment]
Hi there
I just figured that the valgrind tests [were](https://github.com/aviggiano/redis-roaring/pull/89) disabled due to an old redis issue that's already been fixed. 

In any case, after re-enabling it, I wasn't able to reproduce this leak, even though it is quite obvious that `RedisModule_AutoMemory` is missing here. I believe that, in order to reproduce it, there must be a specific sequence of commands that will lose the pointer reference.

[The docs](https://redis.io/topics/modules-api-ref#coderedismoduleautomemorycode) explains that auto memory eliminates the need of calling `RedisModule_CloseKey`, `RedisModule_FreeCallReply` and `RedisModule_FreeString`, so probably it has to do with creating a roaring bitmap, then calling max/min then deleting it??? Not sure...

If you have any ideas (or a sequence of commands to reproduce the bug) I'm happy to add more tests. Otherwise I'll just merge and add a new issue to make the tests more robust

**Comment by arthurkiller** [comment]
> [The docs](https://redis.io/topics/modules-api-ref#coderedismoduleautomemorycode) explain that auto memory eliminates the need of calling `RedisModule_CloseKey`, `RedisModule_FreeCallReply` and `RedisModule_FreeString`, so probably it has to do with creating a roaring bitmap, then calling max/min then deleting it??? Not sure...

LGTM,

```c
/* Mark an object as freed in the auto release queue, so that users can still
 * free things manually if they want.
 *
 * The function returns 1 if the object was actually found in the auto memory
 * pool, otherwise 0 is returned. */
int autoMemoryFreed(RedisModuleCtx *ctx, int type, void *ptr) {
    if (!(ctx->flags & REDISMODULE_CTX_AUTO_MEMORY)) return 0;

... ...

}

```

And I have also investigated in `RedisModule_AutoMemory`. AFAIK, if this is option is switched off, module memory operation such as `FreeString` will not take effect, and memory free should be called manually.

**Comment by aviggiano** [comment]
Merging and opening a new issue here https://github.com/aviggiano/redis-roaring/issues/90 to improve Valgrind tests

**Pull request merged**
