### PR TITLE
flip a bitmap by range

### PR DESCRIPTION
**Pull request by jiangtao244**
fix this:  [https://github.com/aviggiano/redis-roaring/issues/73](url)

### CODE REVIEW

**Review by aviggiano — COMMENTED** [review]
Seems perfect!

Could you just add a test on the `tests/integrations_1.sh` file ?

I believe you could do the exact same test as in issue #73

**Comment by jiangtao244** [comment]
Test added.

Valgrid find some memory leak, is this matter?

**Comment by aviggiano** [comment]
I believe this was already there (related to #2)

I'll merge this PR and create a separate issue to investigate the memory leaks.

**Comment by jiangtao244** [comment]
@aviggiano ,  
Sorry, I missed a test case when lastOffset < Max

Example: 

R.SETINTARRAY src 1 3 5
R.BITOP NOT  dst src  3
R.GETINTARRAY dst

Get:    0 2 5
Expect:  0 2

Need to  cut the bits out of range.

**Pull request merged**
