### PR TITLE
Add diff

### PR DESCRIPTION
**Pull request by egor43**
Added the function of difference bitmaps.

I apologize in advance for my english. This is not my native language.
I am using this library to perform AND / OR operations on growing bitmaps. And for optimization, I need to delete the processed data so as not to do unnecessary work on it in the future. I implemented this function for myself, but it seemed to me that it would be also needed in the original project.

### CODE REVIEW

**Comment by aviggiano** [comment]
Hello @egor43, thank you for contributing.

At a first glance this seems like a very nice feature. Could you please just update the README.md to also include a short description of `R.DIFF`?

Besides that, seems good to merge!

**Comment by egor43** [comment]
Thanks. Of course I will update the README.md

**Comment by egor43** [comment]
Hello @aviggiano  I have updated README.md by adding R.DIFF function description

**Comment by aviggiano** [comment]
Great, thanks for the contribution

**Pull request merged**
